name: tacogfn
channels:
  - anaconda
  - defaults
  - conda-forge
  # - ostrokach-forge 
  # - dglteam
dependencies:
  - python=3.9
  - openbabel>=3.1.1
  - numba=0.57 # pharmaconet
  - rdkit
  - unidock
  - pip
  - pip:
    - -r requirements.txt




  

    
