name: tacogfn
channels:
  - defaults
  # - pytorch
  # - nvidia
  - conda-forge
  - ostrokach-forge 
dependencies:
  - python=3.9
  - openbabel
  - rdkit
  - pip
  - pip:
    - --find-links https://data.pyg.org/whl/torch-1.13.0+cu117.html
    - torch==1.13.0
    - torch-geometric==2.3.1
    - torch-scatter==2.1.1
    - torch-sparse==0.6.17
    - torch-cluster==1.6.1
    - torch-spline-conv 
    - torchdrug==0.2.1
    - -r requirements.txt
