name: tacogfn
channels:
  - anaconda
  - defaults
  - conda-forge
  - ostrokach-forge 
  - dglteam
dependencies:
  - python=3.9
  - openbabel>=3.1.1
  - biopython=1.81 # pharmaconet
  - numpy=1.22.4 # pharmaconet
  - numba=0.57 # pharmaconet
  - rdkit
  - molfeat # molfeat
  - dgllife # molfeat
  - dgl # molfeat
  - pip
  - pip:
    - --find-links https://data.pyg.org/whl/torch-1.13.0+cu117.html
    - torch==1.13.0
    - torch-geometric==2.3.1
    - torch-scatter==2.1.1
    - torch-sparse==0.6.17
    - torch-cluster==1.6.1
    - torch-spline-conv 
    - torchdrug==0.2.1
    - splito
    - umap-learn
    - scipy # pharmaconet
    - timm==0.9 # pharmaconet
    - omegaconf>=2.3 # pharmaconet
    - -r requirements.txt




  

    
